#!/usr/bin/env python3
"""Develop, crop and derive every frame for studio.wirewalk.com.

Sources
  ~/Downloads/wirewalk-photos/selects  the owner's own work (2400px long edge)
  ~/Downloads/wirewalk-photos/flickr   the owner's own work (1600px or 1024px)
  ./stock                              CC0 / public-domain reference frames

Never upscales: a 1024px source simply gets fewer srcset entries. Writes the
derivatives plus the three Jekyll data files the templates read.
"""
import os, glob, json, re
from PIL import Image, ImageOps, ImageEnhance, ImageFilter
from manifest import M

LIB = os.path.expanduser('~/Downloads/wirewalk-photos')
OUT = os.path.expanduser('~/Downloads/studiosite/assets/img')
DATA = os.path.expanduser('~/Downloads/studiosite/_data')
os.makedirs(OUT, exist_ok=True); os.makedirs(DATA, exist_ok=True)
for f in glob.glob(OUT + '/*'): os.remove(f)

gsel = {p['file'][8:-4]: p for p in json.load(open(LIB + '/manifest.json'))['photos']}
flk  = {p['file'][7:-4]: p for p in json.load(open(LIB + '/flickr_manifest.json'))}
sf   = {os.path.basename(f).split('_', 1)[1][:-4]: f for f in glob.glob('stock/*.jpg')}
smeta = json.load(open('stock_keep.json'))

WIDTHS = {'hero': [2000, 1400, 900], 'feature': [1400, 1000, 640],
          'grid': [1000, 640], 'tile': [640, 420]}
JPGW   = {'hero': 1400, 'feature': 1200, 'grid': 800, 'tile': 520}


def develop(im):
    """A light hand: recover black point and white point, a touch of colour."""
    im = ImageOps.autocontrast(im.convert('RGB'), cutoff=(0.22, 0.04), preserve_tone=True)
    return ImageEnhance.Contrast(ImageEnhance.Color(im).enhance(1.05)).enhance(1.035)


def crop_to(im, rw, rh, anchor):
    W, H = im.size; target = rw / rh; cur = W / H
    if abs(cur - target) < 0.002: return im
    if cur > target:                       # too wide: trim both sides evenly
        nw = int(round(H * target)); x = (W - nw) // 2
        return im.crop((x, 0, x + nw, H))
    nh = int(round(W / target))            # too tall: trim to the anchor
    y = max(0, min(H - nh, int(round((H - nh) * anchor))))
    return im.crop((0, y, W, y + nh))


photos, used_stock, used_g, used_l, missing = {}, set(), set(), set(), []
for slug, src, (rw, rh), role, anchor, alt in M:
    key = src[1:]
    if src[0] == 'G':
        if key not in gsel: missing.append((slug, src)); continue
        path, origin = LIB + '/' + (gsel[key].get('use') or gsel[key]['file']), 'selects'; used_g.add(key)
    elif src[0] == 'L':
        if key not in flk: missing.append((slug, src)); continue
        path, origin = LIB + '/' + (flk[key].get('use') or flk[key]['file']), 'flickr'; used_l.add(key)
    else:
        if key not in sf: missing.append((slug, src)); continue
        path, origin = sf[key], 'stock'; used_stock.add(key)

    # A frame with a 'use' path has already been graded by hand. Running the
    # develop pass over it again would stack two sets of contrast moves, which
    # is exactly the fault that made the first retouch pass come out dark.
    src_im = Image.open(path)
    graded = '/retouched/' in path
    im = crop_to(src_im.convert('RGB') if graded else develop(src_im), rw, rh, anchor)
    src_w = im.width
    widths = sorted({w for w in WIDTHS[role] if w <= src_w} or {src_w}, reverse=True)
    webps = []
    for w in widths:
        r = im.resize((w, int(round(w * rh / rw))), Image.LANCZOS) \
              .filter(ImageFilter.UnsharpMask(1.0, 52, 3))
        # Bigger renditions carry more pixels, so they can afford a lower
        # quality for the same perceived result -- and it is the big ones that
        # hurt. Detail-dense frames (snow, foliage) are the worst case, so the
        # ladder is deliberately steep.
        q = 78 if w <= 640 else 72 if w <= 1000 else 64 if w <= 1600 else 58
        fn = f'{slug}-{w}.webp'; r.save(os.path.join(OUT, fn), 'WEBP', quality=q, method=6)
        webps.append((fn, w))
    jw = min(JPGW[role], src_w); jh = int(round(jw * rh / rw))
    r = im.resize((jw, jh), Image.LANCZOS).filter(ImageFilter.UnsharpMask(1.0, 52, 3))
    jfn = f'{slug}-{jw}.jpg'
    jq = 80 if jw <= 640 else 76
    r.save(os.path.join(OUT, jfn), 'JPEG', quality=jq, optimize=True, progressive=True)

    photos[slug] = {'alt': alt, 'ratio': f'{rw}/{rh}', 'src': origin, 'key': key,
                    'w': jw, 'h': jh, 'jpg': f'/assets/img/{jfn}',
                    'webp': ', '.join(f'/assets/img/{f} {w}w'
                                      for f, w in sorted(webps, key=lambda x: x[1]))}

q = lambda s: '"' + str(s).replace('\\', '\\\\').replace('"', '\\"') + '"'
tidy = lambda s: re.sub(r'\s+', ' ', s or '').strip()

with open(DATA + '/photos.yml', 'w') as f:
    f.write("# Generated by tools/build_images.py. One entry per developed, cropped frame.\n"
            "# src: selects|flickr = the owner's own photography; stock = CC0 / public domain.\n")
    for s in sorted(photos):
        p = photos[s]
        f.write(f"{s}:\n  alt: {q(p['alt'])}\n  ratio: {q(p['ratio'])}\n  w: {p['w']}\n"
                f"  h: {p['h']}\n  src: {q(p['src'])}\n  key: {q(p['key'])}\n"
                f"  webp: {q(p['webp'])}\n  jpg: {q(p['jpg'])}\n")

with open(DATA + '/credits.yml', 'w') as f:
    f.write("# Third-party reference frames only. Every licence below was read from the\n"
            "# Wikimedia Commons API (imageinfo extmetadata.LicenseShortName) at the moment\n"
            "# the file was fetched. Nothing listed here is the studio's own work.\n")
    for k in sorted(used_stock, key=int):
        v = smeta[k]
        f.write(f"- id: {q(k)}\n  title: {q(tidy(v['title']).replace('File:', '').rsplit('.jpg', 1)[0])}\n"
                f"  author: {q(tidy(v['artist']) or 'Not stated')}\n  lic: {q(tidy(v['lic']))}\n"
                f"  licurl: {q(tidy(v['licurl']))}\n  page: {q(v['descurl'])}\n")

with open(DATA + '/own.yml', 'w') as f:
    f.write("# The owner's own photography, supplied for this site. Not stock.\n")
    for k in sorted(used_l):
        f.write(f"- id: {q(k)}\n  set: \"Flickr album\"\n  page: {q(flk[k]['page'])}\n")
    for k in sorted(used_g):
        f.write(f"- id: {q(k)}\n  set: \"Studio archive\"\n  desc: {q(gsel[k]['description'])}\n")

print("missing:", missing)
print(f"frames {len(photos)} | own selects {len(used_g)} | own flickr {len(used_l)} | stock {len(used_stock)}")
