# slug, source, ratio(w/h), role, anchor(0=top..1=bottom), alt
# source:  G<name> = ~/Downloads/wirewalk-photos/selects/<name>.jpg   (owner's own)
#          L<name> = ~/Downloads/wirewalk-photos/flickr/<name>.jpg    (owner's own)
#          S<pageid> = CC0 / public-domain reference frame from Wikimedia Commons
# role: hero(2000) feature(1600) grid(1000) tile(640)
M = [
# ══ HERO CONTACT SHEET ═══════════════════════════════════════════════════
("hero-canyon",     "Glandscape-026",(3,2),"hero",   .5, "Canyon walls layered in golden-hour light"),
("hero-city",       "Lcityscape-53783702414",(3,2),"feature",.5,"City waterfront at dusk under a bank of cloud, a bird crossing the frame"),
("hero-smoker",     "Lpeople-53693994437",(4,5),"feature",.3,"Close portrait of an older man outdoors, a cigarette held in his lips"),
("hero-dunes",      "Gwater-193",   (4,5),"feature",.5,"A single bare tree standing in still misted water"),
("hero-dog",        "Gpets-060",   (4,5),"grid",    .5, "Dog standing on a snow-covered track in winter woods"),
("hero-lamp",       "Gmood-058",   (4,5),"grid",    .5, "Snow falling through the light of a park lamp at dusk"),
("hero-pilings",    "Ggraphic-125",(3,2),"feature", .5, "Black and white timber pilings standing in shallow water"),

# ══ FAMILY AND CHILDREN — the owner's own ════════════════════════════════
("fam-grass",       "Gfamily-075",(3,2),"feature",.5,"Young girl sitting in long grass, backlit, the background thrown well out of focus"),
("fam-grass-t",     "Gfamily-075",(4,5),"feature",.45,"Young girl sitting in long grass, backlit in late afternoon"),
("fam-surf",        "Gfamily-169",(3,2),"feature",.5,"Child running through shallow surf, backlit and in monochrome"),
("fam-surf-t",      "Gfamily-169",(4,5),"grid",.45,"Child running through shallow surf, backlit and in monochrome"),
("fam-dress",       "Gfamily-198",(4,5),"feature",.42,"Small child in a purple dress seen from behind, dappled light through trees"),
("fam-dress-w",     "Gfamily-198",(3,2),"grid",.3,"Small child in a purple dress in dappled light"),
("fam-run",         "Gfamily-206",(3,2),"feature",.5,"Child caught mid-run across a lawn, arms out"),
("fam-run-t",       "Gfamily-206",(4,5),"grid",.4,"Child caught mid-run across a lawn, arms out"),

# ══ PEOPLE — the owner's own street portraiture ══════════════════════════
("ppl-smoker",      "Lpeople-53693994437",(3,2),"feature",.4,"Older man outdoors, cigarette in his lips, weathered face filling the frame"),
("ppl-blossom",     "Lpeople-53694883761",(3,2),"grid",.4,"Woman framed by pink blossom, looking past the camera"),
("ppl-blossom-t",   "Lpeople-53694883761",(4,5),"feature",.35,"Woman framed by pink blossom, looking past the camera"),
("ppl-chess",       "Lpeople-53695232234",(3,2),"grid",.5,"Three men bent over a stone chess table in a park"),
("ppl-studio",      "Lpeople-53695324650",(4,5),"grid",.3,"Studio-lit portrait of a woman against a plain warm ground"),
("ppl-reading",     "Lpeople-53695324725",(4,5),"grid",.4,"A man and a child reading together against a bright yellow wall"),
("ppl-lifeguard",   "Lpeople-53750327826",(4,5),"grid",.45,"Lifeguard seated beneath an orange umbrella, tower blocks behind"),
("ppl-surfer",      "Lpeople-53695232139",(3,2),"grid",.5,"Surfer wading out through the shallows carrying a board overhead"),
("ppl-bench",       "Lpeople-53695094818",(3,2),"grid",.5,"Man in a flat cap sitting alone on a park bench among fallen leaves"),
("ppl-bench-2",     "Lpeople-53695232164",(4,5),"grid",.4,"Woman resting on a park bench in autumn light"),
("ppl-grass",       "Lpeople-53695094908",(3,2),"grid",.5,"Two young people sitting together on the grass in late afternoon light"),
("ppl-taichi",      "Lpeople-53693994427",(4,5),"grid",.4,"A line of people practising tai chi along a park path"),
("ppl-quad",        "Lpeople-53695324610",(3,2),"grid",.5,"Beach patrol rider crossing the sand on a quad bike"),
("ppl-angler",      "Lpeople-53765728502",(4,5),"grid",.45,"Lone surfcaster on an empty beach under piled cloud, warm monochrome"),
("ppl-anglers",     "Lpeople-53750451288",(3,2),"grid",.5,"Two anglers sitting out a grey afternoon beside their rods"),
("ppl-bodyboard",   "Lpeople-53872899420",(3,2),"grid",.5,"Bodyboarder walking out of the water as another rider takes a wave"),
("ppl-walk",        "Lpeople-53694883701",(4,5),"tile",.35,"Woman walking a park path in sunglasses, headphones in"),
("ppl-tower",       "Lpeople-53744800312",(3,2),"tile",.5,"Two lifeguards on a yellow beach tower, rescue buoys planted in the sand"),

# ══ CITYSCAPE — the owner's own, largely monochrome ══════════════════════
("city-dusk",       "Lcityscape-53783702414",(3,2),"feature",.5,"City waterfront at dusk, cloud piled above the towers and a bird crossing"),
("city-queensboro", "Lcityscape-53695232134",(3,2),"grid",.5,"Cantilever bridge in black and white with the skyline stacked behind it"),
("city-boardwalk",  "Lcityscape-53763090603",(3,2),"grid",.5,"Boardwalk railing throwing hard diagonal shadows across the deck"),
("city-escalator",  "Lcityscape-53688551789",(4,5),"grid",.5,"Black and white escalators at night, converging metal diagonals"),
("city-pier",       "Lcityscape-53695869206",(3,2),"grid",.5,"Empty timber pier and lamp standards fading into river fog"),
("city-gate",       "Lcityscape-53719444760",(4,5),"grid",.5,"Formal garden stair and gate in black and white, framed by clipped cypress"),
("city-towers",     "Lcityscape-53688419678",(4,5),"grid",.5,"Monochrome cluster of high-rise towers seen from street level"),
("city-cable",      "Lcityscape-53688196626",(3,2),"grid",.5,"Cable car wires strung above a riverside terrace, black and white"),
("city-palms",      "Lcityscape-53740434379",(3,2),"grid",.5,"Two palms flanking an empty beach entrance in near-monochrome"),
("city-bridge",     "Lcityscape-55067526186",(3,2),"grid",.5,"Suspension bridge in black and white with a single sail beneath it"),
("city-drawbridge", "Lcityscape-53749355397",(3,2),"grid",.5,"Drawbridge towers across a flat estuary in black and white"),
("city-rocks",      "Lcityscape-53749376787",(3,2),"grid",.5,"Gulls standing on a rock breakwater, a bridge on the far horizon"),
("city-storm",      "Lcityscape-53784574683",(3,2),"grid",.5,"Waterfront apartment blocks under a heavy grey sky, black and white"),
("city-mansion",    "Lcityscape-53716343232",(3,2),"tile",.5,"Large country house across a wide lawn, black and white"),
("city-canal",      "Lcityscape-53687324357",(3,2),"tile",.5,"Canal-side terrace and stone bridge, a duck in the near water"),
("city-cabanas",    "Lcityscape-53687325502",(3,2),"tile",.5,"Beachfront cabanas and parked cars, printed with a white border"),
("hosp-counter",    "Lcityscape-53746171760",(3,2),"feature",.5,"Counter service at a small restaurant, black and white"),

# ══ LANDSCAPE — the owner's own ══════════════════════════════════════════
("land-canyon",     "Glandscape-026",(3,2),"feature",.5,"Canyon walls stepping back in layers of golden-hour light"),
("land-cumulus",    "Glandscape-067",(3,2),"grid",.5,"Mountain range beneath towering cumulus"),
("land-face",       "Glandscape-144",(4,5),"grid",.5,"Black and white study of a sheer mountain face"),
("land-towers",     "Glandscape-152",(4,5),"grid",.5,"Red rock towers rising against a clear sky"),
("land-dunes-bw",   "Glandscape-159",(3,2),"grid",.5,"Black and white dunes under a bank of cloud"),
("land-dune-ridge", "Glandscape-009",(3,2),"grid",.5,"Sand dune ridge under a deep blue sky, reduced to two shapes"),
("land-dune-crest", "Glandscape-131",(3,2),"grid",.5,"Dune crest cutting a diagonal beneath broken cloud"),
("land-snowpeak",   "Glandscape-298",(3,2),"grid",.5,"Snow peak emerging from cloud"),
("land-meadow",     "Glandscape-295",(3,2),"grid",.5,"Alpine meadow with cloud spilling over the ridge behind it"),
("land-badlands",   "Glandscape-097",(3,2),"grid",.5,"Eroded badlands formation in late light"),
("land-sandstone",  "Glandscape-229",(1,1),"grid",.5,"Sandstone towers under a hard blue sky"),
("land-dune-single","Glandscape-218",(3,2),"tile",.5,"A single dune curve against open sky"),
("land-ridge-cloud","Glandscape-086",(3,2),"tile",.5,"Black and white ridgeline lost in low cloud"),

("wat-bigsur",      "Gwater-019", (3,2),"feature",.5,"Coastline seen from high above, headlands falling away into the Pacific"),
("wat-fisherman",   "Gwater-044", (3,2),"feature",.5,"Lone fisherman silhouetted on absolutely still water"),
("wat-tree",        "Gwater-193", (4,5),"grid",.5,"A single bare tree standing in still misted water"),
("wat-cove",        "Gwater-153", (3,2),"grid",.5,"Turquoise cove enclosed by pale cliffs"),
("wat-deadtree",    "Gwater-213", (3,2),"grid",.5,"Dead tree rooted in turquoise shallows"),
("wat-fog",         "Gwater-270", (3,2),"grid",.5,"Black and white lake in heavy fog, sun burning through the trees"),
("wat-dusk",        "Gwater-294", (4,5),"grid",.5,"Pink dusk over rocks and still water"),
("wat-log",         "Gwater-128", (3,2),"grid",.5,"Black and white lake with a sunken log and cloud reflected"),
("wat-waves-bw",    "Gwater-184", (3,2),"grid",.5,"Black and white waves breaking"),
("wat-iceplant",    "Gwater-158", (3,2),"tile",.5,"Waves running against ice plant on a low bluff"),
("wat-burst",       "Gwater-214", (3,2),"tile",.5,"Monochrome cloud burst over a wide empty beach"),

# ══ GRAPHIC — the line-and-shape work ════════════════════════════════════
("gfx-lifeguard",   "Ggraphic-110",(1,1),"grid",.5,"Yellow lifeguard chair standing against a flat blue sea"),
("gfx-pilings",     "Ggraphic-125",(3,2),"grid",.5,"Black and white pilings standing in shallow water"),
("gfx-arch",        "Ggraphic-149",(4,5),"grid",.5,"Black and white natural rock arch"),
("gfx-escalator",   "Ggraphic-059",(3,2),"grid",.5,"Black and white escalators, strong opposing diagonals"),
("gfx-skyline",     "Ggraphic-202",(3,2),"grid",.5,"Black and white high-rise skyline reduced to blocks of tone"),
("gfx-railing",     "Ggraphic-266",(3,2),"feature",.5,"Pier railing casting a hard repeating shadow across the boards"),
("gfx-boardwalk",   "Ggraphic-022",(3,2),"grid",.5,"Boardwalk running to the horizon in one-point perspective"),
("gfx-rail",        "Ggraphic-189",(3,2),"grid",.5,"Railway track curving away as a single leading line"),
("gfx-road",        "Ggraphic-137",(3,2),"grid",.5,"Monochrome road curving into snowbound mountains"),
("gfx-spillway",    "Ggraphic-230",(3,2),"grid",.5,"Stone arch bridge above a spillway in full flow"),
("gfx-palms",       "Ggraphic-265",(4,5),"tile",.5,"Palm-lined boardwalk running to a vanishing point"),
("gfx-dock",        "Ggraphic-068",(3,2),"tile",.5,"Black and white dock with two palms and a flag"),

# ══ MOOD ═════════════════════════════════════════════════════════════════
("mood-searchlight","Gmood-094", (4,5),"grid",.5,"Searchlight beam thrown over a waterfront gazebo at night"),
("mood-lilies",     "Gmood-041", (3,2),"feature",.5,"Mist lying over a lily-covered lake at dawn"),
("mood-shafts",     "Gmood-000", (3,2),"grid",.5,"Black and white woodland cut by shafts of light"),
("mood-lamp",       "Gmood-058", (3,2),"grid",.5,"Snow falling through the light of a park lamp at dusk"),
("mood-road",       "Gmood-049", (3,2),"grid",.5,"Black and white snow-covered forest road"),
("mood-trunks",     "Gmood-174", (4,5),"grid",.5,"Black and white snow and bare trunks"),
("mood-volcano",    "Gmood-205", (3,2),"grid",.5,"Black and white volcano standing above a small farm"),
("mood-spire",      "Gmood-292", (3,2),"tile",.5,"Black and white rock spire against piled cloud"),

# ══ SEASON ═══════════════════════════════════════════════════════════════
("sea-lane",        "Gseason-290",(4,5),"grid",.5,"Backlit autumn lane, sun coming through the trunks"),
("sea-canopy",      "Gseason-064",(3,2),"grid",.5,"Red maple canopy filling the whole frame"),
("sea-stream",      "Gseason-096",(4,5),"grid",.5,"Autumn stream running between banks of red foliage"),
("sea-canoe",       "Gseason-160",(3,2),"grid",.5,"Red canoe drawn up on an autumn lake shore"),
("sea-mirror",      "Gseason-293",(3,2),"grid",.5,"Autumn shoreline mirrored in still blue water"),
("sea-boards",      "Gseason-120",(3,2),"tile",.5,"Wet autumn leaves scattered across a blue-green boardwalk"),
("sea-shadows",     "Gseason-185",(3,2),"tile",.5,"Bare autumn trees throwing long shadows over leaf litter"),

# ══ DETAIL AND NATURE ════════════════════════════════════════════════════
("det-daisy",       "Gdetail-216",(3,2),"grid",.5,"Grasshopper and a bee sharing the centre of an oxeye daisy"),
("det-ginkgo",      "Gdetail-054",(3,2),"grid",.5,"Ginkgo leaves backlit to a translucent green"),
("det-maples",      "Gdetail-098",(4,5),"grid",.5,"Two maple leaves lying on the forest floor"),
("det-droplets",    "Gdetail-167",(3,2),"grid",.5,"Black and white leaves beaded with water droplets"),
("det-fern",        "Gdetail-207",(3,2),"grid",.5,"Black and white fern frond against dark ground"),
("det-redleaf",     "Gdetail-204",(3,2),"grid",.5,"A single red leaf on pale stone"),
("det-frost",       "Gdetail-093",(3,2),"tile",.5,"Frosted leaves locked under a skin of ice"),
("det-board",       "Gdetail-238",(3,2),"tile",.5,"Red maple leaf on a weathered board"),
("det-reeds",       "Gdetail-239",(4,5),"tile",.5,"Reeds and their reflection in pale blue water"),

# ══ PETS — the owner's own ═══════════════════════════════════════════════
("pet-surf",        "Gpets-047",  (3,2),"feature",.5,"Dog running through the surf at sunrise"),
("pet-track",       "Gpets-060",  (4,5),"grid",.5,"Dog standing on a snow-covered track in winter woods"),
("pet-beach",       "Gpets-107",  (3,2),"grid",.5,"Dog walking a wide empty beach at dawn"),
("pet-trail",       "Gpets-243",  (4,5),"grid",.5,"Dog on a snowy trail, its shadow thrown long toward the camera"),
("pet-bison",       "Gpets-087",  (3,2),"grid",.5,"Bison grazing on open grassland"),

# ══ REFERENCE FRAMES — CC0 / public domain. Never portfolio work. ════════
("ref-headshot-01", "S61874612", (4,5),"grid",.32,"Reference frame: corporate headshot against a plain grey backdrop"),
("ref-headshot-02", "S61724220", (4,5),"grid",.32,"Reference frame: studio headshot against a pale background"),
("ref-headshot-03", "S61733565", (4,5),"grid",.35,"Reference frame: environmental portrait shot outdoors in low sun"),
("ref-atwork-desk", "S61682185", (3,2),"feature",.5,"Reference frame: someone working at a desk behind a glass partition"),
("ref-atwork-office","S61683440",(4,5),"grid",.5,"Reference frame: a person working at a long table in a daylit office"),
("ref-atwork-bench","S61684689", (3,2),"grid",.5,"Reference frame: hands working a piece of material on a workshop bench"),
("ref-atwork-drill","S61682731", (3,2),"grid",.5,"Reference frame: hands operating a pillar drill in a dark workshop"),
("ref-atwork-weld", "S58828446", (3,2),"grid",.5,"Reference frame: welder at work inside a steel structure"),
("ref-atwork-timber","S61681532",(3,2),"grid",.5,"Reference frame: two people measuring and cutting timber on site"),
("ref-meeting",     "S58798558", (3,2),"grid",.5,"Reference frame: two people in conversation across a table of notebooks"),
("ref-collab",      "S61739139", (3,2),"grid",.5,"Reference frame: a group working around a table spread with a map"),
("ref-boardroom",   "S58854696", (3,2),"grid",.5,"Reference frame: boardroom table and chairs before a wall of windows"),
("ref-loft",        "S61803840", (3,2),"grid",.5,"Reference frame: meeting table in a brick-walled loft office"),
("ref-atrium",      "S62070191", (4,5),"grid",.5,"Reference frame: glazed office atrium seen from an upper floor"),
("ref-lounge",      "S61714494", (3,2),"tile",.5,"Reference frame: informal office lounge with sofa and low table"),
("ref-tower",       "S61879295", (3,2),"tile",.5,"Reference frame: office towers above a public plaza"),
("ref-prod-cans",   "S62191354", (3,2),"grid",.5,"Reference frame: a hand holding headphones against plain white"),
("ref-prod-cans-bw","S61803610", (3,2),"grid",.5,"Reference frame: studio-lit headphones photographed low key"),
("ref-prod-camera", "S62212736", (4,5),"grid",.5,"Reference frame: medium format camera on a tripod head, side-lit"),
("ref-prod-watch",  "S61876343", (3,2),"grid",.5,"Reference frame: wristwatch photographed close, shallow focus"),
("ref-prod-bottle", "S61848404", (3,2),"grid",.5,"Reference frame: bottle and filled glass on a table against open water"),
("ref-prod-kit",    "S61713629", (1,1),"grid",.5,"Reference frame: pour-over coffee equipment on a clean white ground"),
("ref-prod-flat",   "S62286798", (3,2),"tile",.5,"Reference frame: cameras and film boxes laid out on a dark surface"),
("ref-re-lounge",   "S61716283", (3,2),"grid",.5,"Reference frame: interior lounge with brick wall and window planting"),
("ref-re-bedroom",  "S62122306", (3,2),"grid",.5,"Reference frame: bright bedroom with desk, plant and low bed"),
("ref-re-stairwell","S61874763", (4,5),"grid",.5,"Reference frame: curved stairwell from above with a figure on the landing"),
("ref-re-spiral",   "S62280902", (4,5),"grid",.5,"Reference frame: spiral staircase photographed from directly above"),
("ref-re-sofa",     "S61880151", (1,1),"grid",.5,"Reference frame: yellow sofa shot from overhead on pale terrazzo"),
("ref-re-stairs",   "S62068008", (3,2),"grid",.5,"Reference frame: white exterior stairs against a bright wall"),
("ref-re-linen",    "S61847874", (3,2),"tile",.5,"Reference frame: unmade bed in soft window light"),
("ref-re-drawer",   "S62119968", (3,2),"tile",.5,"Reference frame: open kitchen drawer with cutlery in a wooden insert"),
("ref-re-concrete", "S62086001", (3,2),"grid",.5,"Reference frame: board-marked concrete meeting sky on a hard diagonal"),
("ref-re-glass",    "S62208011", (4,5),"grid",.5,"Reference frame: black and white abstract of a folding glass facade"),
("ref-ev-concert",  "S61688449", (3,2),"grid",.5,"Reference frame: performer silhouetted against stage lights above a crowd"),
("ref-ev-lights",   "S62064892", (3,2),"grid",.5,"Reference frame: concert crowd under blue and violet stage beams"),
("ref-ev-gig",      "S62195667", (4,5),"grid",.45,"Reference frame: black and white singer at the front of a small stage"),
("ref-ev-festival", "S61670009", (3,2),"grid",.5,"Reference frame: festival crowd under strings of lights at dusk"),
("ref-wed-field",   "S61708623", (3,2),"grid",.45,"Reference frame: couple forehead to forehead in a field at sunset"),
("ref-wed-columns", "S61710036", (3,2),"grid",.5,"Reference frame: bride and groom before a colonnaded building"),
("ref-wed-aisle",   "S61710778", (4,5),"grid",.5,"Reference frame: aisle set for a ceremony with tall floral arrangements"),
("ref-wed-rings",   "S61734111", (3,2),"tile",.5,"Reference frame: two wedding rings resting on an open book"),
("ref-food-plate",  "S61663167", (3,2),"grid",.5,"Reference frame: plated dish photographed from directly above"),
("ref-food-prep",   "S62054003", (3,2),"grid",.5,"Reference frame: hands slicing vegetables thinly on a wooden board"),
("ref-food-room",   "S61911723", (3,2),"grid",.5,"Reference frame: restaurant dining room at service"),
("ref-food-cup",    "S61717405", (1,1),"tile",.5,"Reference frame: espresso and a glass of milk on a wooden table"),
("ref-drone",       "S62191359", (3,2),"grid",.5,"Reference frame: quadcopter hovering above a lake shore"),
("ref-drone-ctrl",  "S62084690", (3,2),"grid",.5,"Reference frame: hands on a drone controller, live view above the coast"),
("ref-aerial-city", "S61633678", (3,2),"grid",.5,"Reference frame: high aerial view across a dense city of towers"),
("ref-aerial-wood", "S61775456", (1,1),"grid",.5,"Reference frame: aerial view straight down onto autumn woodland"),
("ref-vid-lens",    "S62379052", (3,2),"feature",.5,"Reference frame: long telephoto lens on a body at the edge of a field"),
("ref-vid-operator","S61878777", (3,2),"grid",.5,"Reference frame: operator shouldering a cinema camera in a kitchen"),
("ref-vid-slr",     "S62121072", (3,2),"grid",.5,"Reference frame: 35mm SLR on a table, shallow focus on the barrel"),
("ref-vid-barrel",  "S61754620", (4,5),"grid",.5,"Reference frame: low-key study of a lens barrel and aperture ring"),
("ref-vid-photog",  "S61835793", (4,5),"tile",.5,"Reference frame: photographer working handheld on an empty road"),
("ref-aud-console", "S61692790", (3,2),"feature",.5,"Reference frame: faders and rotary controls along a mixing console"),
("ref-aud-mic",     "S62059665", (4,5),"grid",.5,"Reference frame: condenser microphone on a shock mount, lit low key"),
("ref-aud-cans",    "S61803610", (4,5),"tile",.5,"Reference frame: studio headphones photographed low key against black"),
]
